### ISSUE TITLE
IndexOutOfBoundsException in the Decoder

### ISSUE THREAD

**Issue by madebyTimo** [kevinstadler/JavaMP3#2]
Hello,
on many but not on all mp3s I get a  java.lang.IndexOutOfBoundsException Exception int the Decoder.java at line 1784 and I don't know why. I also wasn't able to find out which characteristic causes this problems. Thank you for your help!

**Comment by kevinstadler** [comment]
Making good progress at this in #3, most IndexOutOfBoundsException errors should be fixed in the next version of the sound library coming out in the next few days.
